---

local_host: "192.168.1.102:20090"
service_host: "192.168.1.102:20091"
mongo_host: "192.168.1.102:27017"

#生成key:openssl genrsa -out server.key 2048
#生成.crt:openssl req -new -x509 -sha256 -key server.key -out server.crt -days 3650
cer_path: "/Users/ws/.ssh/pem_test"

etcd_server: #etcd服务配置
 endpoints:
  - "http://10.10.18.179:22379"
  - "http://10.10.18.179:2379"
  - "http://10.10.18.179:32379"
 dial_timeout:  50 #超时时间秒为单位
 user_name: "root"
 password: "12345678"